### PR TITLE
Refractor usrcheck.py

### PR DESCRIPTION
**Pull request by SenhasD**
Removed hashlib import
Made code smaller while it has all the previous functions

### CODE REVIEW

**Comment by SenhasD** [comment]
Cannot add hashlib to hash passwords without proper authorisation from the owner

**Comment by 1to5pc** [comment]
> Cannot add hashlib to hash passwords without proper authorisation from the owner

Yeah, no, not hashing plaintext passwords is a big security vulnerability.

**Comment by 1to5pc** [comment]
Maybe streamline the code but keep in mission-critical features.

**Comment by SenhasD** [comment]
> Maybe streamline the code but keep in mission-critical features.

Lol you should have made the hash thing before me then

**Comment by 1to5pc** [comment]
> > Maybe streamline the code but keep in mission-critical features.
> 
> Lol you should have made the hash thing before me then

It was there from the start?

**Pull request closed without merging**
